services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python ./__main__.py  
    volumes:
      - ./backend:/app
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://username:password@db:5432/dbname
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:

